[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "deny"

[workspace.dependencies]
rukata-puzzle-data = { path="crates/rukata-puzzle-data" }
rukata-puzzles = { path="crates/rukata-puzzles" }
rukata-settings = { path="crates/rukata-settings" }
