[package]
name = "rukata-puzzles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rukata-puzzle-data.workspace = true

[lints]
workspace = true
