[package]
name = "rukata-puzzle-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rukata-puzzle-config.workspace = true

[lints]
workspace = true
